exports.jsAssets = require('./jsAssets')
exports.jsDependencies = require('./jsDependencies')
exports.cssAssets = require('./cssAssets')
exports.cssDependencies = require('./cssDependencies')
exports.htmlAssets = require('./htmlAssets')
exports.vueAssets = require('./vueAssets')
exports.vueDependencies = require('./vueDependencies')
